### ISSUE TITLE
Slow Clackers

### ISSUE THREAD

**Issue by ReefKit** [met4000/clicker.clicker#10]
Clackers must have upgrades which increase their speed. Otherwise, at the moment, just buying clickers will more efficient for a loooooong time. I can see the potential in clackers, but upgrades must allow it to become faster. If upgrades are added, they will be really good, because at first, they don't do much, but if you upgrade them, they become O.P. :DD
-Mr_Kit

**Comment by ReefKit** [comment]
Sorry, ignore what I said. I just did some maths and found out that they still work very well, looking at how many times they will be purchased. DON'T focus on making upgrades which increase the speed of the tower. You can if you want to, but the upgrades should be kept to a minimum, ok? :DD

**Comment by met4000** [comment]
Upgrades will be coming for clackers, but they won't upgrade speed...
