### ISSUE TITLE
First 'report error' on clicker.clicker! :DD

### ISSUE THREAD

**Issue by ReefKit** [met4000/clicker.clicker#9]
I just got the latest version of clicker.clicker from development and currently testing it (while making images for it at the same time). Now I don't know if this is a error. But when I am in the tab, I am making 10 cps. But when I'm in another tab, I am only making 1 cps. What's happening here? ;-;

Btw, FIRST!!! (reference to Youtube comments :P )

-Mr_Kit

**Comment by met4000** [comment]
Reference to also almost any forum with suspected popular mods/updates/etc.... Anyways, have you bought anything or upgraded anything? What version is it? Where is it (e.g. scibi, downloaded release, etc.)? Could you please post some screenshots.

**Comment by ReefKit** [comment]
Well, currently when I'm in the tab, I get about 11m/s, but out of the tab I get 2000/s. I don't know if you put this in or not. And taking screen shots wouldn't help since it's a still image, not a moving one. The only upgrades I have are the first 3 clicker upgrades and the first 3 cursor upgrades. I have 186 clackers.

**Comment by met4000** [comment]
11 m/s? Do you mean c/s?

**Comment by met4000** [comment]
Also, what version, and obtained/operating from where. Actually, what browser is it as well; it's designed and has been tested solely in chrome.

**Comment by met4000** [comment]
How many clickers and cursors?

**Comment by met4000** [comment]
Could you please post the save code, as well?

**Comment by met4000** [comment]
Okay. Testing revealed that all cps changes to "1 cps" while out of tab. Also, no clickers were produced by clackers. I suspect a problem with setInterval() when "out of tab".

**Comment by met4000** [comment]
After brief research, when a tab becomes inactive, setInterval() changes to 1 or 2 p sec, as opposed to what it is set to. This means that you will only have 1cps from inactive tabs. I may or may not fix this...

**Comment by met4000** [comment]
Patch available and will be in code, but not enabled by default (and therefore try and deter people from AFK farming).
